### ISSUE TITLE
Field "transmission" is required to make a mechanism

### ISSUE THREAD

**Issue by ThijsRoumen** [janetzki/Mechanism-Browser#39] opened 2018-05-31 13:09 UTC
In general: no field should be required I think 

![screenshot 2018-05-31 15 08 33](https://user-images.githubusercontent.com/1307670/40784036-a4f2edd8-64e4-11e8-85a5-a801ff3ff0ad.png)

**Comment by janetzki** [comment] 2018-06-05 10:26
Closed as a duplicate of #21

**Closed by janetzki** 2018-06-05 10:26 UTC
Labels: duplicate
