### ISSUE TITLE
I propose to make a feature to show that you dont know something

### ISSUE THREAD

**Issue by ThijsRoumen** [janetzki/Mechanism-Browser#55] opened 2018-06-12 12:19 UTC
this makes it evident for somebody else that this still needs to be calculated, can be a simple checkbox 
so in this case I may not know the exact transmission ratio (would have to be calculated) but the mechanism is interesting as such. Anyone else should be able to come in and modify that

![screenshot 2018-06-12 14 19 01](https://user-images.githubusercontent.com/1307670/41289937-9c1a16a8-6e4b-11e8-8991-7501337e73be.png)

**Comment by janetzki** [comment] 2018-08-11 19:05
Closed as a duplicate of #59.

**Closed by janetzki** 2018-08-11 19:05 UTC
Labels: duplicate, frontend, ✨ feature
